
class UserExistsException(Exception):
    pass

class UserNotFoundException(Exception):
    pass